# # ................................................................
# # ................................................................
# # Main script to call for the analysis and rendering ClimMob reports
# # ................................................................
# # ................................................................

# get the arguments from server's call
#args <- commandArgs(trailingOnly = TRUE)
infoname    <- args[1] # a json file with parameters for the analysis
outputname  <- args[2] # a json file with the results
pathname    <- args[3] # the path where results will be written
infosheets  <- as.logical(args[4]) # logical, if infosheets should be written TRUE FALSE
language    <- args[5] # the language to write the report "en" for english and "es" for spanish
extension   <- args[6] # report file format it can be "docx", "pdf", and "html"
ranker      <- args[7] # how the system will refer to participants/farmers
option      <- args[8] # how the system will refer to tested items
fullpath    <- args[9] # this is backward path
reference   <- args[10] # the reference item for the analysis
if (isTRUE(is.na(reference))) {
  reference <- 1
}

# Two objects to begin with that will be used to verify the process
error <- NULL
done <- TRUE

# ................................................................
# ................................................................
# Read data #### 
# Read data with selected traits and explanatory variables to be analysed
try_pars <- tryCatch({
  pars <- jsonlite::fromJSON(infoname)
  pars <- ClimMobTools:::.decode_pars(pars)
}, error = function(e) {
    e$message <-
      paste(
        "Error 101. There was a problem reading the json file with the",
        "parameters required to perform the analysis."
      )
  }
)

if (isTRUE(grepl("Error 101", try_pars))) {
  error <- c(error, try_pars)
  done <- FALSE
}

# Read as json and add the class "CM_list" so it can be passed to as.data.frame 
# method from ClimMobTools
try_cmdata <- tryCatch({
  cmdata <- jsonlite::fromJSON(outputname)
  class(cmdata) <- union("CM_list", class(cmdata))
  cmdata <- as.data.frame(cmdata, tidynames = FALSE, pivot.wider = TRUE)
  
  quest <- jsonlite::fromJSON(outputname)
  quest <- quest[["specialfields"]]
  
}, error = function(e) {
  e$message <-
    paste(
      "Error 102. There was a problem reading the json file with the",
      "ClimMob data."
    )
}
)

if (isTRUE(grepl("Error 102", try_cmdata))) {
  error <- c(error, try_cmdata)
  done <- FALSE
}

# ................................................................
# ................................................................
# Run analysis ####
tryCatch({
  dir.create(pathname, showWarnings = FALSE, recursive = TRUE)
})

if (isTRUE(done)) {
  source(paste0(fullpath, "/R/analysis_climmob.R"))
}


# ................................................................
# ................................................................
# Write outputs ####
#determine format based on extensions
output_format <- ifelse(extension == "docx","word_document", 
                        paste0(extension,"_document"))

# produce the reports
if (isTRUE(done)) {
  
  # the main report
  try_rep <- tryCatch({
    rmarkdown::render(paste0(fullpath, "/report/", language, "/mainreport.Rmd"),
                      output_dir = pathname,
                      output_format = output_format,
                      output_file = paste0("climmob_main_report", ".", extension))
  }, error = function(e) {
    e$message <-
      paste(
        "Error 115. There was a problem producing the report file with the output",
        "generated by the requested analysis."
      )
  }
  )
  
  if (isTRUE(grepl("Error 115", try_rep))) {
    error <- c(error, try_rep)
    done <- FALSE
  }
}

if (all(infosheets, done)) {
  
  tryCatch({
    dir.create(paste0(pathname, "/participant_report/png"),  
               showWarnings = FALSE, recursive = TRUE)
  })
  
  try_infosheet <- tryCatch({
    source("R/participant_report.R")
  }, error = function(e){
    e$message <-
      paste(
        "Error 115. There was a problem writing the participants report(s)."
      )
  })
  
  if (isTRUE(grepl("Error 115", try_infosheet))) {
    error <- c(error, try_infosheet)
  }
  
}

# if there was any error in the analysis, produce a error report 
if (isFALSE(done)) {
  rmarkdown::render(paste0(fullpath, "/report/", language, "/mainreport_failed.Rmd"),
                    output_dir = pathname,
                    output_format = output_format,
                    output_file = paste0("climmob_main_report", ".", extension))
}


