
**`r other_traits_list[[i]]$fullname`**

```{r, include=FALSE, echo=FALSE}
if (ncomp == 3){
    R2 <- rank_tricot(data = cmdata[other_traits_list[[i]]$keep, ],
                      items = itemnames,
                      input = other_traits_list[[i]]$input)
}
  
if (ncomp > 3) {
    R2 <- rank_numeric(data = cmdata[other_traits_list[[i]]$keep, ],
                       items = itemnames,
                       input = other_traits_list[[i]]$input)
}



fav1 <- summarise_favorite(R2)
fav2 <-fav1

fav2$best <- paste0(round(fav2$best, 1), "%")
fav2$worst <- paste0(round(fav2$worst, 1), "%")
fav2$fav_score <- round(fav2$fav_score, 1)

fav2 <- fav2[,-which(grepl("wins", names(fav2)))]

names(fav2) <- c(Option,"N","Top Ranked","Bottom Ranked",
                 "Net Favourability Score")

p2 <- 
  plot(fav1) +
  xlab("") +
  theme_minimal() +
  theme(axis.text.x = element_text(size = 10, color = "#000000"),
        axis.text.y = element_text(size = 10, color = "#000000"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "none")

```

```{r}
knitr::kable(fav2[nrow(fav2):1,],
             row.names = FALSE,
             caption = paste0("Table 2.2.",i,". Favourability statistics for '",
                           tolower(other_traits_list[[i]]$fullname),"'"))
```

\

```{r, dpi=dpi, fig.height=favplot_h, fig.width=6, fig.cap= paste0("Figure 2.2.",i, ". Net favourability score for '",tolower(other_traits_list[[i]]$fullname),"'.")}
p2
```
