**`r other_traits_list[[i]]$fullname`**


```{r}
x_tmp <- anovas[[i]]
if (length(x_tmp)>1) {
  p_tmp <- x_tmp[2,5]
  
  x_tmp[,6] <- stars.pval(x_tmp[, 5])
  x_tmp[,5] <- format.pval(x_tmp[, 5])
  names(x_tmp)[6] <- ""
  x_tmp[2, "model"] <- other_traits_list[[i]]$fullname

  kable(x_tmp,
        caption = paste0("Table 4.",i,".1. Likelihood ratio test results from fitted Plackett-Luce model with rankings from '", tolower(other_traits_list[[i]]$fullname), "'."))
}

```

\

```{r}
message_tmp=""
if (length(x_tmp) > 1) {
if (p_tmp < 0.001) {
  message1 <- paste0("p=", format.pval(p_tmp), 
                    ". This suggests that there is strong evidence of ",
                    "a difference in the rankings between ",
                    options)
}

if (p_tmp < 0.01 & p_tmp > 0.001) {
  message1 <- paste0("p=", format.pval(p_tmp), 
                     ". This suggests that there is evidence of a difference between ",
                     options)
}
if (p_tmp > 0.01 & p_tmp < 0.05) {
  message1 <- paste0("p=", format.pval(p_tmp), 
                    ". This suggests that there is some evidence of a difference between ",
                    options)  
}
if (p_tmp > 0.05) {
  message1 <- paste0("p=", format.pval(p_tmp),
                    ". This suggests that there is not enough evidence to conclude that",
                    " there are differences between",
                    options)  
}
}
if(length(x_tmp) == 1){
  message_tmp <- "No statistical analysis was able to be conducted on this characteristic."
}
```

`r message_tmp`

\

```{r,dpi=dpi, fig.width=7,fig.height=7, fig.cap=paste0("Figure 4.",i,".1. Model coefficients and mean separation of Plackett-Luce model for '", tolower(other_traits_list[[i]]$fullname),"' with ", ci_level*100, "% confidence intervals.")}

if(length(x_tmp)>1){
  plot.multcompPL(summaries[[i]], level = ci_level)
}
```

\

```{r}
if (length(x_tmp) > 1) {
  ms_i <- summaries[[i]]
  ms_i <- ms_i[, c("estimate","quasiSE",".group")]
  names(ms_i) <- c("Estimate","quasiSE","Group")
  
  kable(ms_i, digits = 2,
        caption = paste0("Table 4.",i,".1. Model coefficients and mean separation of Plackett-Luce model for '",
                         tolower(other_traits_list[[i]]$fullname),"' with ", ci_level*100, "% confidence intervals."))
}
```

\

```{r}
if (length(x_tmp) > 1) {


kable(worths[[i]][,-2],
      caption = paste0("Table 4.",i,".3 ","Percetage probability of being highest ranked for '",
                      tolower(other_traits_list[[i]]$fullname), "'."))
}
```

\

```{r, dpi=dpi, fig.width=7,fig.height=7, fig.cap=paste0("Figure 4.",i,".2. Prabability of being the best ranked for '", tolower(other_traits_list[[i]]$fullname),"'.")}
dt_i <- worths[[i]]

ggplot(data=dt_i, aes(y = Worth, fill = Worth, group = dt_i[,1], x = 1)) +
  geom_bar(stat="identity",col="black", show.legend = FALSE) +
  theme_void() +
  geom_text(aes(y=cumsum(rev(Worth))-rev(Worth)/2, size=rev(Worth),
                label=rev(paste0(dt_i[,1],": ", round(Worth*100, 2),"%"))),
            show.legend = FALSE,fontface=2) +
  scale_fill_gradient2(low= "#ffffff", high = "#2ca25f", midpoint= 1/nrow(worthscaled))  +
  scale_size_continuous(range=c(0.5,10),limits = c(0,1))
```

